services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: placepoll-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - placepoll-net

networks:
  placepoll-net:
    name: placepoll-net
    driver: bridge
